name: "Gradle"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "25 6 * * 5"

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

env:
  JAVA_VERSION: 17

jobs:
  validate:
    name: "Validate"
    runs-on: "ubuntu-latest"
    permissions: read-all
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1

  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    needs: "validate"
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up JDK ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"

      - name: "Build"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: "build"